language: c
dist: trusty
sudo: false

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - libssl-dev
        - libtool-bin
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: osx
    compiler: clang

script:
  - .travis/all-tests.sh
