language: c
dist: trusty
sudo: true

matrix:
  include:
  - os: linux
    compiler: arm-linux-gnueabi-gcc
    addons:
      apt:
        packages:
        - gcc-arm-linux-gnueabi
        - libc6-dev-armel-cross
        - qemu
    script:
    - scripts/arm-cross-compile.sh
    - scripts/arm-run-tests-qemu.sh
  - os: osx
    compiler: clang
    env:
    - CC_OVERRIDE=clang
    - WITH_OPENSSL=1
    before_install:
    - brew install doxygen graphviz
    - pip3 install pytest
    script:
    - .travis/all-tests.sh
  - os: osx
    compiler: clang
    env:
    - CC_OVERRIDE=clang
    - WITH_OPENSSL=0
    before_install:
    - brew install doxygen graphviz
    - pip3 install pytest
    script:
    - .travis/all-tests.sh
