language: c
dist: trusty
sudo: false

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - doxygen
        - graphviz
        - gcc-7
        - libssl-dev
    env:
      - ARCH=x64
      - CC_OVERRIDE=gcc-7
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - doxygen
        - graphviz
        - gcc-7
        - libssl-dev
    env:
      - ARCH=x86
      - CC_OVERRIDE=gcc-7
  - os: osx
    compiler: clang
    before_install:
      - brew install doxygen
      - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/0c4314c499576b28e4c082b591228a8f940954c0/Formula/clang-format.rb
      - brew switch clang-format 2016-06-27
    env:
      - ARCH=x64
      - CC_OVERRIDE=clang

script:
  - .travis/all-tests.sh
