version: 1.0.{build}

image: Visual Studio 2017

platform: x64

build:
  verbosity: minimal

branches:
  except:
    - /.*nist.*/
    - /master-new-.*/

init:
  - set PATH="C:\\Python37";"C:\\Python37\Scripts";%PATH%


configuration:
  - Debug
  - DebugDLL
  - Release
  - ReleaseDLL

test_script:
- cmd: >-
    python -m pip install pytest

    cd %APPVEYOR_BUILD_FOLDER%

    python -m pytest -v
