version: 2

.oqsjob: &oqsjob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout
    - run: autoreconf -i
    - run: ./configure --enable-silent-rules ${CONFIGURE_ARGS}
    - run: make -j
    - run: make check
    - run: python3 -m pytest -v

jobs:
  debian-buster-amd64:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:amd64-buster-0.0.4
      SKIP_TESTS: style
  ubuntu-trusty-x86_64-gcc47:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-trusty-0.0.1
      CC: gcc-4.7
      CONFIGURE_ARGS: --disable-sig-picnic
      SKIP_TESTS: style
  ubuntu-trusty-x86_64-gcc48:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-trusty-0.0.1
      CC: gcc-4.8
      CONFIGURE_ARGS: --disable-sig-picnic
      SKIP_TESTS: style
  ubuntu-xenial-x86_64-gcc49:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-xenial-0.0.5
      CC: gcc-4.9
      CONFIGURE_ARGS: --disable-sig-picnic
  ubuntu-xenial-x86_64-gcc5:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-xenial-0.0.5
      CC: gcc-5
  ubuntu-xenial-x86_64-gcc6:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-xenial-0.0.5
      CC: gcc-6
  ubuntu-xenial-x86_64-gcc7:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-xenial-0.0.5
      CC: gcc-7
  ubuntu-xenial-x86_64-gcc8:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-xenial-0.0.5
      CC: gcc-8
  ubuntu-xenial-x86_64-gcc8-noopenssl:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-xenial-0.0.5
      CC: gcc-8
      CONFIGURE_ARGS: --without-openssl
  ubuntu-xenial-x86_64-gcc8-noshared:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-xenial-0.0.5
      CC: gcc-8
      CONFIGURE_ARGS: --disable-shared
  ubuntu-bionic-x86_64-gcc7:
    <<: *oqsjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-bionic-0.0.1
      CC: gcc-7
      SKIP_TESTS: style

workflows:
  version: 2
  build:
    jobs:
      - debian-buster-amd64
      - ubuntu-trusty-x86_64-gcc47
      - ubuntu-xenial-x86_64-gcc8
      - ubuntu-xenial-x86_64-gcc8-noopenssl
      - ubuntu-xenial-x86_64-gcc8-noshared
      - ubuntu-bionic-x86_64-gcc7
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - debian-buster-amd64
      - ubuntu-trusty-x86_64-gcc47
      - ubuntu-trusty-x86_64-gcc48
      - ubuntu-xenial-x86_64-gcc49
      - ubuntu-xenial-x86_64-gcc5
      - ubuntu-xenial-x86_64-gcc6
      - ubuntu-xenial-x86_64-gcc7
      - ubuntu-xenial-x86_64-gcc8
      - ubuntu-xenial-x86_64-gcc8-noopenssl
      - ubuntu-xenial-x86_64-gcc8-noshared
      - ubuntu-bionic-x86_64-gcc7
